name: futminna-appointment-system

services:
  mongo:
    image: mongo:7.0
    container_name: futminna_ams_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: futminna_ams
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futminna_ams_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/futminna_ams
      - NEXTAUTH_SECRET=futminna_ams_super_secret_local_key_change_me_in_production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - uploads_data:/app/public/uploads

volumes:
  mongo_data:
    driver: local
  uploads_data:
    driver: local
